
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: http-monitoring
  namespace: monitoring
spec:
  parentRefs:
  - name: istio-gateway
    namespace: istio-gateway
  hostnames: ["gazami.click"]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /monitoring/argocd
    backendRefs:
    - name: argocd-server
      port: 443
  - matches:
    - path:
        type: PathPrefix
        value: /monitoring/grafana
    backendRefs:
    - name: kube-prometheus-stack-grafana
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /monitoring/kiali
    backendRefs:
    - name: kiali
      port: 20001

