apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: "anonymous"
  istio_namespace : "istio-system"
  deployment: 
    accessible_namespaces: ["**"]
    namespace: "monitoring"
  service_type: ClusterIP
  server:
    web_port: 20001
    web_root: /monitoring/kiali
  external_services:
    prometheus:
      url: "http://kube-prometheus-stack-prometheus.monitoring:9090/"


