
---
apiVersion: v1
kind: Service
metadata:
  namespace: istio-gateway
  name: service-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nginx
# ---