apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret
  namespace: sql
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
  databaseName: final_project
  dbUserName: bigdata